name: ArksnUtils
version: '${project.version}'
main: fr.arikkusan.arksnutils.Main
api-version: 1.19
authors: [ Arikkusan ]
description: Plugin giving other plugins dependent on mine plenty of commands and necessary functions
commands:
  password:
    description: Allow player to log in and to be able to move
    usage: /<command> <KEY>
    aliases: [p]
  CustomName:
    description: Allow player to set their own Custom name
    usage: /<command>
    aliases: [cst]
  gm:
    description: Put the user in gm1 / gm0
    usage: /<command>